#!/bin/bash

# name:    plot_diff_finger_pdf.sh
# authors: Paolo Raiteri, Andrew Rohl, Norwid Behrnd
# license: GPLv2, or later
# edit:    2019-11-04 (YYYY-MM-DD)
#
# Bash script to plot differences of Hirshfeld fingerprints with gnuplot
#
# The script anticipates the .dat file previously generated by the 
# executable of diff_finger.c as input.  It will truncate the last four
# characters (.dat) of the file name to use this as an internal label on
# the plot provided as .pdf vector file.  The color scheme deployed in the
# map discerns blue (negative), white (zero-level), and red (positive) for
# the difference of normalized fingerprint_A minus normalized fingerprint_B.
#
# On the CLI, your instructions follow the pattern of:
#
# chmod u+x plot_diff_finger_pdf.sh      # provision of the executable bit
# ./plot_diff_finger_pdf.sh example.dat  # generation of the .pdf plot
#
# to generate example.pdf.
#
# While set up in an outer format of 6.0 x 6.0 cm (about 2.4 x 2.4 in),
# optionally, you may trim the margin subsequently.  As example, Heiko
# Oberdiek's pdfcrop will yield with
#
# pdfcrop --margins 1 infile.pdf outfile.pdf
#
# a .pdf with a box of 2.18 x 1.86 in (about 5.5 x 4.7 cm).

gnuplot  -e "
  input = '$1';
  len_root = strlen(input) - 4;
  root = substr(input, 1, len_root);
  output_file = root . '.pdf';
  set output(output_file);

  set term pdfcairo size 6cm,6cm font 'Arial,8' enha lw 1;
  set grid lw 0.5; set size square;
  set xtics 0.4,0.2; set ytics 0.4,0.2;
  set xtics format '%2.1f'; set ytics format '%2.1f';
  set label 'd_e' at graph 0.07,0.90 left front;
  set label 'd_i' at graph 0.90,0.07 left front;
  set label root at graph 0.07,0.07 left front noenhanced;

  set pm3d map;
  unset key;
  set palette defined (-1 'blue', 0 'white', 1 'red');
  set g;
  set cbrange [-0.025:0.025];
  sp'$1' u 1:2:3  w p pt 5 ps 0.001 lc palette z"

# END
